sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.6
before_install:
  - docker run --name etcd quay.io/coreos/etcd:v3.1.0
  - sudo apt-get install consul;
  - consul agent -dev;
script:
  - make
notifications:
  email:
    recipients:
      - aditya@portworx.com
    on_success: always
    on_failure: always
